# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import echo_pb2 as proto_dot_echo__pb2


class TestDuplexServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/fullDuplexTest.TestDuplexService/Echo',
        request_serializer=proto_dot_echo__pb2.EchoRequest.SerializeToString,
        response_deserializer=proto_dot_echo__pb2.EchoResponse.FromString,
        )
    self.Bid = channel.stream_stream(
        '/fullDuplexTest.TestDuplexService/Bid',
        request_serializer=proto_dot_echo__pb2.FullDuplexRequest.SerializeToString,
        response_deserializer=proto_dot_echo__pb2.FullDuplexRequest.FromString,
        )
    self.send = channel.unary_unary(
        '/fullDuplexTest.TestDuplexService/send',
        request_serializer=proto_dot_echo__pb2.FullDuplexRequest.SerializeToString,
        response_deserializer=proto_dot_echo__pb2.FullDuplexResponse.FromString,
        )


class TestDuplexServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Bid(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestDuplexServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=proto_dot_echo__pb2.EchoRequest.FromString,
          response_serializer=proto_dot_echo__pb2.EchoResponse.SerializeToString,
      ),
      'Bid': grpc.stream_stream_rpc_method_handler(
          servicer.Bid,
          request_deserializer=proto_dot_echo__pb2.FullDuplexRequest.FromString,
          response_serializer=proto_dot_echo__pb2.FullDuplexRequest.SerializeToString,
      ),
      'send': grpc.unary_unary_rpc_method_handler(
          servicer.send,
          request_deserializer=proto_dot_echo__pb2.FullDuplexRequest.FromString,
          response_serializer=proto_dot_echo__pb2.FullDuplexResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fullDuplexTest.TestDuplexService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
